version: '3.0'

services:


  # Dummy PG db to simulate a e2e trace system
  postgres1:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
